### ISSUE TITLE
mvt-fixtures contains large mason_packages

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mvt-fixtures#100]
It looks like mvt-fixtures was published with unintended data, leading to a 55MB download. This is quite large and leads mvt-fixtures to be the largest single source of size in downstream repos. This is hazardous for users with slow network. By ignoring `mason_packages` it looks like we can save 18 MB. By moving `real-world` to a different repo we could save another 33 MB.

/cc @mapsam

**Comment by mapsam** [comment]
Yikes. Good catch @springmeyer - I had totally forgotten mason packages would be around after running our `./script/dump` debugger. I'll publish a new patch removing this!
