### ISSUE TITLE
Multiple geometry fields (test 030)

### ISSUE THREAD

**Issue by joto** [mapbox/mvt-fixtures#36]
The Google Protobuf spec [says](https://developers.google.com/protocol-buffers/docs/encoding) that a non-repeated field can actually appear several times in a message and the implementation is required to return the value of the last version of that field in this case. So we can not do the check that this fixture asks for!

**Comment by mapsam** [comment]
Oh interesting! Leaving here for posterity:

> Normally, an encoded message would never have more than one instance of a non-repeated field. However, parsers are expected to handle the case in which they do. For numeric types and strings, if the same field appears multiple times, the parser accepts the last value it sees. For embedded message fields, the parser merges multiple instances of the same field, as if with the Message::MergeFrom method – that is, all singular scalar fields in the latter instance replace those in the former, singular embedded messages are merged, and repeated fields are concatenated.

@joto do you think it's worth updating the fixture description to specify that decoders will choose the _last_ instance, and update it to a valid fixture?

**Comment by joto** [comment]
Looking at this again I see that the geometry is a packed repeated field, so this case is a bit different. Having multiple geometries in the way this test does it would mean they have to be concatenated (as per protobuf spec), but we do not support this in vtzero (https://github.com/mapbox/vtzero/blob/master/doc/advanced.md#differences-between-the-specification-and-the-vtzero-implementation).

**Comment by mapsam** [comment]
@joto it seems like this fixture may not be helpful for vtzero, but I'll plan on keeping it around for other possible decoders. Feel free to reopen if there is still an issue with this feature.
