### ISSUE TITLE
how to includes these in a c++ library?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#4]
What would be the best way to include these fixtures in a C++ library? Some thoughts:

* could publish mason somehow?
* git submodule
* npm install in a C++ project and pointing to node_modules

cc @springmeyer @GretaCB @flippmoke @artemp

**Comment by springmeyer** [comment]
👍  git submodule and for people/projects that would prefer not to use submodules just vendorizing (since these fixtures will not get updated very often, right?)

**Comment by mapsam** [comment]
I agree 👍
