### ISSUE TITLE
Generated fixtures seem to use proto3

### ISSUE THREAD

**Issue by joto** [mapbox/mvt-fixtures#47]
I think the fixtures are generated using `proto3` syntax instead of `proto2` syntax.

To parse the proto file protocol-buffers-schema js lib is used which [defaults to version 3](https://github.com/mafintosh/protocol-buffers-schema/blob/master/parse.js#L578). This can be overwritten by using `syntax = "proto2";` in the `.proto` file, but then some older pbf parsers can't read the file any more, so that's why this shouldn't be in the proto file.

Problem is now that some things are slightly different in different protobuf versions, which makes the encoding of the tile using `pbf` lib wrong. In this case I found it, because fixture 013 generates not a `repeated uint32 keys` field, but a `repeated uint32 keys [packed = true]` field. In proto3 there are no unpacked repeated fields, so the `pbf` lib is doing the right thing here for proto3, but we should be using proto2.

Took me a while to dig through this and I haven't actually tried it, but just looked at the code, but I think this is where the problem is. This might affect more test fixtures, too.

**Comment by mapsam** [comment]
Yikes, good catch @joto. Perhaps we can add `syntax = "proto2";` to the proto file before generating the buffer - so it won't actually go into the specification but is used just for the generation of the buffer. I'll give this a try and see how many fixtures change.

**Comment by mapsam** [comment]
Resolved in #48
