### ISSUE TITLE
real world fixtures

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#49]
Per chat with Jochen, we think it could be helpful to include some real-world fixtures in this library as well. These would be exactly like https://github.com/mapbox/mvt-bench-fixtures but stored here to keep them under one repository, rather than relying on multiple submodules. 

I know we've strayed away from complex test cases - but I think we could keep them here without getting in the way of generating fixtures. Perhaps we just have a fixtures/real-world directory to dump them in?

cc @springmeyer @joto @flippmoke @GretaCB @millzpaugh

**Comment by springmeyer** [comment]
👍 to adding them here as long as they are organized separately.

**Comment by mapsam** [comment]
Resolved in #60
