### ISSUE TITLE
Fixture 041: strings/floats

### ISSUE THREAD

**Issue by joto** [mapbox/mvt-fixtures#51]
The description says the tags are "encoded as strings", but they are encoded as floats.

**Comment by joto** [comment]
The doc should probably mention that this is not detectable from the protobuf encoding alone. A decoder will interpret these floats as varints (which suceeds in this case) and only notice later that they point to non-existing indexes.

**Comment by mapsam** [comment]
Woops - forgot to update the description. Thanks @joto! I'll add the note you mention as well.

**Comment by mapsam** [comment]
@joto is it fair to say that the error handling should be "fatal" here? Or is that mostly dependent on the decoder and the use-case?

**Comment by joto** [comment]
This is a bit tricky. If you are not looking at the properties, this case will not result in an error, so we can not mark it as "fatal". Maybe we need an "its complicated" option. :-)

**Comment by mapsam** [comment]
Haha, maybe the entire "validity" section should be prefaced with "it's complicated" 😄 

I wonder if instead of creating standard around the possible values for `error` in the fixtures, we write a `recommendation` for how to handle the situation.

**Comment by joto** [comment]
It is still useful to have the valid vs. fatal distinction for more simple-minded tests, but yes, some more detailed explanation especially for the more complex test cases would maybe be more useful for the tester.

**Comment by mapsam** [comment]
Fixed in #52
