### ISSUE TITLE
valid fixtures

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#6]
Let's bring in valid fixtures here as well. No need to be pure evil. 

- [x] rename repository/project to `mvt-fixtures`
- [x] split into `/valid` and `/invalid` directories
- [x] re-release to npm
- [x] deprecate evilmvt (but #neverforget)

cc @springmeyer @flippmoke @GretaCB

**Comment by springmeyer** [comment]
👍

**Comment by mapsam** [comment]
@mapbox/evilmvt `<= 1.0.0` has been deprecated on npm with the following message: "Package has been renamed to @mapbox/mvt-fixtures, please upgrade."

New module created at https://www.npmjs.com/package/@mapbox/mvt-fixtures

This is done!
