### ISSUE TITLE
Fixture 009 validity/extent is present?

### ISSUE THREAD

**Issue by joto** [mapbox/mvt-fixtures#64]
Description says there is no extent, but extent is in the tile.json file. Also this should be valid, because of defaulting.

See also #33.

**Comment by mapsam** [comment]
Planning on continuing to call this "invalid" according to the vector tile **specification**, but the README has a note for validity and references that defaults may be enabled depending on the decoder. Updated the tile.json in https://github.com/mapbox/mvt-fixtures/pull/69

**Comment by springmeyer** [comment]
This fixture is still marked as invalid, but it is valid because decoders can/should handle missing properties that will defaults with proto2 per #33

**Comment by mapsam** [comment]
While recognizing this is a big grey area, I don't 100% agree that this is valid - considering the actual specification says it is invalid if the extent is missing. I'd feel comfortable marking this as "valid" once the specification is updated to note that proto versions may handle this differently.

**Comment by mapsam** [comment]
Considering updating the spec probably won't happy fast, I'll update to mark as "valid" and make sure the GOTCHA is updated to include `extent` as an example as well. https://github.com/mapbox/mvt-fixtures/#usage
