### ISSUE TITLE
gunzip real-world fixtures?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#66]
The real-world fixtures are all gzipped (which is confusing since they don't include `.gz` extensions), so there are a few ideas here:

👟  unzip them all and store as raw buffers in the repo/module (increases module size)
👞  update file extension, that's it 
👡  update file extension, build in function (at least for JS downstreams) to get a real world buffer unzipped

I'm in favor of 👟 

cc @mapbox/core-tech

**Comment by springmeyer** [comment]
Also in favor of 👟.

**Comment by joto** [comment]
Agree. Having the raw data keeps the issue of compression out of scope here.

That being said, having one set of tiles with different types of compression would be good, too, to test compression and file-type-autodetection code.

**Comment by mapsam** [comment]
Cool - uncompressed it is. 

After looking into these "compressed" tiles it appears that they are, in fact, already uncompressed. When running gunzip:

```
gunzip: 13-2102-3047.mvt.gz: not in gzip format
```

I've downloaded the file directly in the browser and it comes out as a different byte size (32 KB versus 37 KB from request.js). It results in a `unknown pbf field type exception` in both vtzero and vtinfo, suggesting it's corrupt. Haven't been able to dig into _why_ they are corrupt yet.

**Comment by springmeyer** [comment]
One guess is that request is interpreting the data as utf8. Can you try setting `encoding=null` in the options per https://github.com/request/request/#requestoptions-callback
