### ISSUE TITLE
Tiles with huge geometries

### ISSUE THREAD

**Issue by joto** [mapbox/mvt-fixtures#73]
We should have tiles containing geometries that pretend to be huge to test for huge memory allocations and such. It is easy to craft a geometry like this. Just pretend it contains lots and lots of points (they don't actually have to be there, just the count). Max value for the count is 2^29-1.

**Comment by springmeyer** [comment]
👍  We should do this - thanks for ticketing @joto - is this something you can work on next week?

**Comment by joto** [comment]
See https://github.com/mapbox/vtzero/blob/master/test/t/test_geometry.cpp#L297-L306 for an example how this is tested in vtzero.

**Comment by mapsam** [comment]
Added two new fixtures with a large MoveTo and LineTo commands in #88
