### ISSUE TITLE
More real-world tiles needed

### ISSUE THREAD

**Issue by joto** [mapbox/mvt-fixtures#76]
The real-worls tiles we currently have seem to be all from mapbox streets. I think we need tiles from different sources, such as OSM QA tiles or tiles created by tippecanoe for those visualizations @ericfischer has been doing, etc. The more diverse the tiles are, the better we can make sure we are not developing code that works well with some tiles but fails or is slow in different use cases.

**Comment by mapsam** [comment]
💯 agree @joto - I haven't used the OSM QA tiles before, would you mind pointing me to where I can get these?

**Comment by joto** [comment]
https://osmlab.github.io/osm-qa-tiles/

**Comment by mapsam** [comment]
@joto thanks! Anywhere in the world you'd like to get tiles from? I'll extra ~20 of them.

**Comment by joto** [comment]
Good mixture of different features (points, linestrings, geometries), dense/sparse, and different zoom levels.

**Comment by mapsam** [comment]
@joto I have a PR ready with two different geographies from OSM QA https://github.com/mapbox/mvt-fixtures/pull/77 - they include Barbados and Andorra

Two things:

1. osm qa is only tiled at z12, so we can't choose different zooms 
1. many of the tiles exceed the 500k limit so hosting on mapbox.com isn't possible (which is necessary to allow others to edit/update the extents source file and re-download)

**Comment by joto** [comment]
If they are too big for fixtures, we'll need some different way of accessing them. The whole point of the fixtures collection is to get a wide variety of tiles for testing, benchmarking etc. so I think it is important to have access to those "XXL tiles", too. Not sure why you want to upload to mapbox.com?

Maybe we can leave it at what you have in #77 and add a note to the README how and where you can get more tiles? Or some kind of script in here that downloads a collection of tiles "on demand".

**Comment by mapsam** [comment]
> important to have access to those "XXL tiles", too

Agree

> Not sure why you want to upload to mapbox.com?

Specifically for the script we have that allows you to download a collection of tiles on demand. Basically using it to host tiles, so we can update bounding boxes and re-download if necessary. That said, I suppose we could create an alternate code-path to download the MBTiles and extract tiles via node-mbtiles ... but this introduces more dependencies than I'd like (i.e. node-sqlite3).

---

It looks like OSM QA tiles haven't been updated since 2015, so it feels important to get a few more recent sources. Any other sources you'd like to see in here?

**Comment by ericfischer** [comment]
That is alarming to hear that the OSM QA tiles are so far behind. `curl -I https://s3.amazonaws.com/mapbox/osm-qa-tiles-production/latest.planet.mbtiles.gz` says they were updated yesterday: `Last-Modified: Mon, 13 Nov 2017 09:15:54 GMT`. Where are you seeing the 2015?

**Comment by mapsam** [comment]
Oops, @ericfischer I was just looking at the commit history of the website. Didn't realize the tiles weren't hosted there. Nevermind!

**Comment by mapsam** [comment]
@joto I've gone ahead and added osm qa tiles without uploading to Mapbox in #77 - I think my hesitations around "how to update" shouldn't be a blocker. Will merge this and release in 3.2.0!

**Comment by mapsam** [comment]
Going to close this now that we have mapbox streets, mapbox terrain, and OSM qa tiles. If any other sources are desired, please open a separate ticket!
