### ISSUE TITLE
Missing a Feature-single-multipolygon.mvt

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mvt-fixtures#8]
I noticed we are missing a multipolygon example.

/cc @BergWerkGIS @mapsam

**Comment by BergWerkGIS** [comment]
What about this one: https://github.com/mapbox/vector-tile-cs/blob/84e9944b5f57eab31960450f29b5fa614d0d9d4e/data/14-8902-5666.test.pbf

Contains 
* point
* multipoint
* linestring 
* multi-linestring
* polygon
* multi-polygon
* polygon with inner ring
* multi-polygon with inner ring

![image](https://cloud.githubusercontent.com/assets/4549888/20090479/9aa8d1ac-a58d-11e6-8d21-5878529b5da3.png)

**Comment by springmeyer** [comment]
The idea of `mvt-fixtures` is to contain the least possible, most simple data. So we only want a single feature, with the same attributes as the other `Feature-single-*` files, but with a single multipolygon.

**Comment by mapsam** [comment]
👍 to @springmeyer's approach, though I think it's worth including a fixture that has ALL geometry types as well. I think we should add both.

**Comment by springmeyer** [comment]
> though I think it's worth including a fixture that has ALL geometry types as well. I think we should add both.

👎 My preference would be to focus mvt-fixtures on excellent coverage while being as small and descrete as possible. Instead of storing it, a fixture with ALL geometries types could be easily auto-generated by a client of mvt-fixtures by concatenating the buffers of all the `Feature-single-*` files.

**Comment by mapsam** [comment]
Alright with me @springmeyer!

**Comment by mapsam** [comment]
Added a multipolygon fixture in https://github.com/mapbox/mvt-fixtures/pull/32 using the example provided in the spec readme: https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4356-example-multi-polygon
