### ISSUE TITLE
More property type fixtures

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mvt-fixtures#81]
Per https://codecov.io/gh/mapbox/vtvalidate/src/master/src/vtvalidate.cpp#L53, adding fixtures for varied property types.

cc @mapsam

**Comment by mapsam** [comment]
@GretaCB will [fixture 038](https://github.com/mapbox/mvt-fixtures/blob/master/src/038.js) do the trick here?

I had a hard time searching for the fixture in FIXTURES.md - might be worth updating the description to include the words "all property types" or something similar.

**Comment by GretaCB** [comment]
@mapsam heck yes, did the trick 🎉 . I'll add the word "property" to the description (I CTRL+F'd initially when looking for relevant fixtures)

**Comment by mapsam** [comment]
Terrific - thanks @GretaCB!
