### ISSUE TITLE
[new fixture] tile with "painted" geometry (clipped square)

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#83]
A tile with a single polygon geometry that covers the entire extent of the tile. This covers the case where a tile only represents a portion of the original geometry, and is completely within it the original geometry - referred to as "painted".

Will work on putting together the command integers for this one.

cc @mapbox/core-tech

**Comment by springmeyer** [comment]
👍  to having this. Though I'm not seeing positive value in keeping the `painted` term alive, which exists more from trying to translate (poorly) the idea of a "uniformly colored ocean tile" from image tiles to vector tiles. 

How about "clipped square" or "buffered clipped square" for fixture descriptions (we should probably have one clipped exactly on the tile boundary, one with -1 and 4097 geometry range, and one way outside (8192 or more?).

**Comment by mapsam** [comment]
> clipped square

👍  nice @springmeyer - happy to phase out "painted".

**Comment by mapsam** [comment]
These were added in #87 and will ship with the next release!
