### ISSUE TITLE
Is invalid/Value-multiple-fields.mvt actually invalid?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#9]
According to the spec, the `Value` field can be repeated, which means multiple values is not invalid. Maybe this was meant for the `valid` pool?

cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
I would say if the two values differ then it is valid.
If the values are the same:

> It is not invalid — just heavily not suggested
> which means a decoders must not throw on it, but could warn on it

😏

**Comment by BergWerkGIS** [comment]
@mapsam this one is valid: 2 different values:
![image](https://cloud.githubusercontent.com/assets/4549888/20340599/9c3b6d44-abe2-11e6-94b0-23c0df267da8.png)

**Comment by mapsam** [comment]
Excellent - thanks @BergWerkGIS!

**This fixture is valid.** Let's rename and add to the `valid` bucket.
