### ISSUE TITLE
Dump script fails due to missing vector-tile-spec

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mvt-fixtures#92]
When I tried to use `dump`, I got "vector-tile-spec/2.1/vector_tile.proto: No such file or directory".  The script appears to expect the https://github.com/mapbox/vector-tile-spec repo to exist as a subdirectory:

https://github.com/mapbox/mvt-fixtures/blob/d015ae587d7c4654c5f705ded69f2d02a3cc0397/scripts/dump#L23

**Comment by joto** [comment]
The vector tile specs are included as a submodule. You must call `git submodule update --init` in the mvt-fixtures directory after the `git clone` and before doing anything else. This should

**Comment by anandthakker** [comment]
🤦‍♂️  completely missed that. Thanks.
